//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blend.SterlingImplementation.SterlingIBService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SterlingIBService.IBSServicesSoap")]
    public interface IBSServicesSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridge", ReplyAction="*")]
        Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponse IBSBridge(Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridge", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponse> IBSBridgeAsync(Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeNE", ReplyAction="*")]
        Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponse IBSBridgeNE(Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeNE", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponse> IBSBridgeNEAsync(Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeAppzone", ReplyAction="*")]
        Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponse IBSBridgeAppzone(Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBSBridgeAppzone", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponse> IBSBridgeAppzoneAsync(Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridge", Namespace="http://tempuri.org/", Order=0)]
        public Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequestBody Body;
        
        public IBSBridgeRequest() {
        }
        
        public IBSBridgeRequest(Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeRequestBody() {
        }
        
        public IBSBridgeRequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponseBody Body;
        
        public IBSBridgeResponse() {
        }
        
        public IBSBridgeResponse(Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeResult;
        
        public IBSBridgeResponseBody() {
        }
        
        public IBSBridgeResponseBody(string IBSBridgeResult) {
            this.IBSBridgeResult = IBSBridgeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeNERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeNE", Namespace="http://tempuri.org/", Order=0)]
        public Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequestBody Body;
        
        public IBSBridgeNERequest() {
        }
        
        public IBSBridgeNERequest(Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeNERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeNERequestBody() {
        }
        
        public IBSBridgeNERequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeNEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeNEResponse", Namespace="http://tempuri.org/", Order=0)]
        public Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponseBody Body;
        
        public IBSBridgeNEResponse() {
        }
        
        public IBSBridgeNEResponse(Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeNEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeNEResult;
        
        public IBSBridgeNEResponseBody() {
        }
        
        public IBSBridgeNEResponseBody(string IBSBridgeNEResult) {
            this.IBSBridgeNEResult = IBSBridgeNEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeAppzoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeAppzone", Namespace="http://tempuri.org/", Order=0)]
        public Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequestBody Body;
        
        public IBSBridgeAppzoneRequest() {
        }
        
        public IBSBridgeAppzoneRequest(Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeAppzoneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string request;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Appid;
        
        public IBSBridgeAppzoneRequestBody() {
        }
        
        public IBSBridgeAppzoneRequestBody(string request, int Appid) {
            this.request = request;
            this.Appid = Appid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IBSBridgeAppzoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IBSBridgeAppzoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponseBody Body;
        
        public IBSBridgeAppzoneResponse() {
        }
        
        public IBSBridgeAppzoneResponse(Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IBSBridgeAppzoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IBSBridgeAppzoneResult;
        
        public IBSBridgeAppzoneResponseBody() {
        }
        
        public IBSBridgeAppzoneResponseBody(string IBSBridgeAppzoneResult) {
            this.IBSBridgeAppzoneResult = IBSBridgeAppzoneResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBSServicesSoapChannel : Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSServicesSoapClient : System.ServiceModel.ClientBase<Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap>, Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap {
        
        public BSServicesSoapClient() {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponse Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap.IBSBridge(Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest request) {
            return base.Channel.IBSBridge(request);
        }
        
        public string IBSBridge(string request, int Appid) {
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest inValue = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest();
            inValue.Body = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponse retVal = ((Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap)(this)).IBSBridge(inValue);
            return retVal.Body.IBSBridgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponse> Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap.IBSBridgeAsync(Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest request) {
            return base.Channel.IBSBridgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeResponse> IBSBridgeAsync(string request, int Appid) {
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest inValue = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequest();
            inValue.Body = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap)(this)).IBSBridgeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponse Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap.IBSBridgeNE(Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest request) {
            return base.Channel.IBSBridgeNE(request);
        }
        
        public string IBSBridgeNE(string request, int Appid) {
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest inValue = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest();
            inValue.Body = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponse retVal = ((Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap)(this)).IBSBridgeNE(inValue);
            return retVal.Body.IBSBridgeNEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponse> Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap.IBSBridgeNEAsync(Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest request) {
            return base.Channel.IBSBridgeNEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeNEResponse> IBSBridgeNEAsync(string request, int Appid) {
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest inValue = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequest();
            inValue.Body = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeNERequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap)(this)).IBSBridgeNEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponse Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap.IBSBridgeAppzone(Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest request) {
            return base.Channel.IBSBridgeAppzone(request);
        }
        
        public string IBSBridgeAppzone(string request, int Appid) {
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest inValue = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest();
            inValue.Body = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponse retVal = ((Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap)(this)).IBSBridgeAppzone(inValue);
            return retVal.Body.IBSBridgeAppzoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponse> Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap.IBSBridgeAppzoneAsync(Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest request) {
            return base.Channel.IBSBridgeAppzoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneResponse> IBSBridgeAppzoneAsync(string request, int Appid) {
            Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest inValue = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequest();
            inValue.Body = new Blend.SterlingImplementation.SterlingIBService.IBSBridgeAppzoneRequestBody();
            inValue.Body.request = request;
            inValue.Body.Appid = Appid;
            return ((Blend.SterlingImplementation.SterlingIBService.IBSServicesSoap)(this)).IBSBridgeAppzoneAsync(inValue);
        }
    }
}
