//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blend.ProvidusImplementation.AirtimeTopup
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "urn:Reseller_iTopUp_wsdl", ConfigurationName = "AirtimeTopup.Reseller_iTopUp_wsdlPort")]
    public interface Reseller_iTopUp_wsdlPort
    {

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message EchoCheckRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#EchoCheck", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.EchoCheckResponse EchoCheck(Blend.ProvidusImplementation.AirtimeTopup.EchoCheckRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message ResellerBalanceRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#ResellerBalance", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.ResellerBalanceResponse ResellerBalance(Blend.ProvidusImplementation.AirtimeTopup.ResellerBalanceRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message FlexiTransactionDetailRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#FlexiTransactionDetail", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetailResponse FlexiTransactionDetail(Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetailRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message FixTransactionDetailRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#FixTransactionDetail", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetailResponse FixTransactionDetail(Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetailRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message FlexiRechargeRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#FlexiRecharge", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.FlexiRechargeResponse FlexiRecharge(Blend.ProvidusImplementation.AirtimeTopup.FlexiRechargeRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message FixRechargeRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#FixRecharge", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.FixRechargeResponse FixRecharge(Blend.ProvidusImplementation.AirtimeTopup.FixRechargeRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message FlexiVoidRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#FlexiVoid", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.FlexiVoidResponse FlexiVoid(Blend.ProvidusImplementation.AirtimeTopup.FlexiVoidRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message FixVoidRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#FixVoid", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.FixVoidResponse FixVoid(Blend.ProvidusImplementation.AirtimeTopup.FixVoidRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message OpenRechargeRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#OpenRecharge", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.OpenRechargeResponse OpenRecharge(Blend.ProvidusImplementation.AirtimeTopup.OpenRechargeRequest request);

        // CODEGEN: Generating message contract since the wrapper namespace (http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl.php) of message ActivationDeactivationRequest does not match the default value (urn:Reseller_iTopUp_wsdl)
        [System.ServiceModel.OperationContractAttribute(Action = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
            ".php#Reseller_iTopUp_wsdl#ActivationDeactivation", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true, Use = System.ServiceModel.OperationFormatUse.Encoded)]
        Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivationResponse ActivationDeactivation(Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivationRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class EchoCheck_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string messageField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class ActivationDeactivation_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class ActivationDeactivation_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string activationDeactivationTypeField;

        private string startRangeField;

        private string endRangeField;

        private string discountField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string ActivationDeactivationType
        {
            get
            {
                return this.activationDeactivationTypeField;
            }
            set
            {
                this.activationDeactivationTypeField = value;
                this.RaisePropertyChanged("ActivationDeactivationType");
            }
        }

        /// <remarks/>
        public string StartRange
        {
            get
            {
                return this.startRangeField;
            }
            set
            {
                this.startRangeField = value;
                this.RaisePropertyChanged("StartRange");
            }
        }

        /// <remarks/>
        public string EndRange
        {
            get
            {
                return this.endRangeField;
            }
            set
            {
                this.endRangeField = value;
                this.RaisePropertyChanged("EndRange");
            }
        }

        /// <remarks/>
        public string Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
                this.RaisePropertyChanged("Discount");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class OpenRecharge_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string confirmationCodeField;

        private int requestIdField;

        private string auditNoField;

        private int topUpAmountField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string ConfirmationCode
        {
            get
            {
                return this.confirmationCodeField;
            }
            set
            {
                this.confirmationCodeField = value;
                this.RaisePropertyChanged("ConfirmationCode");
            }
        }

        /// <remarks/>
        public int RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string AuditNo
        {
            get
            {
                return this.auditNoField;
            }
            set
            {
                this.auditNoField = value;
                this.RaisePropertyChanged("AuditNo");
            }
        }

        /// <remarks/>
        public int TopUpAmount
        {
            get
            {
                return this.topUpAmountField;
            }
            set
            {
                this.topUpAmountField = value;
                this.RaisePropertyChanged("TopUpAmount");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class OpenRecharge_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string requestIdField;

        private string batchIdField;

        private string operatorCodeField;

        private string mobileNumberField;

        private string amountField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string BatchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
                this.RaisePropertyChanged("BatchId");
            }
        }

        /// <remarks/>
        public string OperatorCode
        {
            get
            {
                return this.operatorCodeField;
            }
            set
            {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("OperatorCode");
            }
        }

        /// <remarks/>
        public string MobileNumber
        {
            get
            {
                return this.mobileNumberField;
            }
            set
            {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("MobileNumber");
            }
        }

        /// <remarks/>
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FixVoid_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string confirmationCodeField;

        private string auditNoField;

        private int topUpAmountField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string ConfirmationCode
        {
            get
            {
                return this.confirmationCodeField;
            }
            set
            {
                this.confirmationCodeField = value;
                this.RaisePropertyChanged("ConfirmationCode");
            }
        }

        /// <remarks/>
        public string AuditNo
        {
            get
            {
                return this.auditNoField;
            }
            set
            {
                this.auditNoField = value;
                this.RaisePropertyChanged("AuditNo");
            }
        }

        /// <remarks/>
        public int TopUpAmount
        {
            get
            {
                return this.topUpAmountField;
            }
            set
            {
                this.topUpAmountField = value;
                this.RaisePropertyChanged("TopUpAmount");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FixVoid_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string requestIdField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FlexiVoid_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string confirmationCodeField;

        private string auditNoField;

        private int topUpAmountField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string ConfirmationCode
        {
            get
            {
                return this.confirmationCodeField;
            }
            set
            {
                this.confirmationCodeField = value;
                this.RaisePropertyChanged("ConfirmationCode");
            }
        }

        /// <remarks/>
        public string AuditNo
        {
            get
            {
                return this.auditNoField;
            }
            set
            {
                this.auditNoField = value;
                this.RaisePropertyChanged("AuditNo");
            }
        }

        /// <remarks/>
        public int TopUpAmount
        {
            get
            {
                return this.topUpAmountField;
            }
            set
            {
                this.topUpAmountField = value;
                this.RaisePropertyChanged("TopUpAmount");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FlexiVoid_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string requestIdField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FixRecharge_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string confirmationCodeField;

        private int requestIdField;

        private string auditNoField;

        private int topUpAmountField;

        private string providerResponseField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string ConfirmationCode
        {
            get
            {
                return this.confirmationCodeField;
            }
            set
            {
                this.confirmationCodeField = value;
                this.RaisePropertyChanged("ConfirmationCode");
            }
        }

        /// <remarks/>
        public int RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string AuditNo
        {
            get
            {
                return this.auditNoField;
            }
            set
            {
                this.auditNoField = value;
                this.RaisePropertyChanged("AuditNo");
            }
        }

        /// <remarks/>
        public int TopUpAmount
        {
            get
            {
                return this.topUpAmountField;
            }
            set
            {
                this.topUpAmountField = value;
                this.RaisePropertyChanged("TopUpAmount");
            }
        }

        /// <remarks/>
        public string ProviderResponse
        {
            get
            {
                return this.providerResponseField;
            }
            set
            {
                this.providerResponseField = value;
                this.RaisePropertyChanged("ProviderResponse");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FixRecharge_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string requestIdField;

        private string batchIdField;

        private string systemServiceIDField;

        private string referalNumberField;

        private string fromANIField;

        private string emailField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string BatchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
                this.RaisePropertyChanged("BatchId");
            }
        }

        /// <remarks/>
        public string SystemServiceID
        {
            get
            {
                return this.systemServiceIDField;
            }
            set
            {
                this.systemServiceIDField = value;
                this.RaisePropertyChanged("SystemServiceID");
            }
        }

        /// <remarks/>
        public string ReferalNumber
        {
            get
            {
                return this.referalNumberField;
            }
            set
            {
                this.referalNumberField = value;
                this.RaisePropertyChanged("ReferalNumber");
            }
        }

        /// <remarks/>
        public string FromANI
        {
            get
            {
                return this.fromANIField;
            }
            set
            {
                this.fromANIField = value;
                this.RaisePropertyChanged("FromANI");
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FlexiRecharge_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string confirmationCodeField;

        private string requestIdField;

        private string auditNoField;

        private int topUpAmountField;

        private string providerResponseField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string ConfirmationCode
        {
            get
            {
                return this.confirmationCodeField;
            }
            set
            {
                this.confirmationCodeField = value;
                this.RaisePropertyChanged("ConfirmationCode");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string AuditNo
        {
            get
            {
                return this.auditNoField;
            }
            set
            {
                this.auditNoField = value;
                this.RaisePropertyChanged("AuditNo");
            }
        }

        /// <remarks/>
        public int TopUpAmount
        {
            get
            {
                return this.topUpAmountField;
            }
            set
            {
                this.topUpAmountField = value;
                this.RaisePropertyChanged("TopUpAmount");
            }
        }

        /// <remarks/>
        public string ProviderResponse
        {
            get
            {
                return this.providerResponseField;
            }
            set
            {
                this.providerResponseField = value;
                this.RaisePropertyChanged("ProviderResponse");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FlexiRecharge_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string requestIdField;

        private string batchIdField;

        private string systemServiceIDField;

        private string referalNumberField;

        private string amountField;

        private string fromANIField;

        private string emailField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string BatchId
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
                this.RaisePropertyChanged("BatchId");
            }
        }

        /// <remarks/>
        public string SystemServiceID
        {
            get
            {
                return this.systemServiceIDField;
            }
            set
            {
                this.systemServiceIDField = value;
                this.RaisePropertyChanged("SystemServiceID");
            }
        }

        /// <remarks/>
        public string ReferalNumber
        {
            get
            {
                return this.referalNumberField;
            }
            set
            {
                this.referalNumberField = value;
                this.RaisePropertyChanged("ReferalNumber");
            }
        }

        /// <remarks/>
        public string Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }

        /// <remarks/>
        public string FromANI
        {
            get
            {
                return this.fromANIField;
            }
            set
            {
                this.fromANIField = value;
                this.RaisePropertyChanged("FromANI");
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FixTransactionDetail_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string transactionResponseCodeField;

        private string transactionResponseDescriptionField;

        private string confirmationCodeField;

        private string auditNoField;

        private int topUpAmountField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string TransactionResponseCode
        {
            get
            {
                return this.transactionResponseCodeField;
            }
            set
            {
                this.transactionResponseCodeField = value;
                this.RaisePropertyChanged("TransactionResponseCode");
            }
        }

        /// <remarks/>
        public string TransactionResponseDescription
        {
            get
            {
                return this.transactionResponseDescriptionField;
            }
            set
            {
                this.transactionResponseDescriptionField = value;
                this.RaisePropertyChanged("TransactionResponseDescription");
            }
        }

        /// <remarks/>
        public string ConfirmationCode
        {
            get
            {
                return this.confirmationCodeField;
            }
            set
            {
                this.confirmationCodeField = value;
                this.RaisePropertyChanged("ConfirmationCode");
            }
        }

        /// <remarks/>
        public string AuditNo
        {
            get
            {
                return this.auditNoField;
            }
            set
            {
                this.auditNoField = value;
                this.RaisePropertyChanged("AuditNo");
            }
        }

        /// <remarks/>
        public int TopUpAmount
        {
            get
            {
                return this.topUpAmountField;
            }
            set
            {
                this.topUpAmountField = value;
                this.RaisePropertyChanged("TopUpAmount");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FixTransactionDetail_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string requestIdField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FlexiTransactionDetail_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string transactionResponseCodeField;

        private string transactionResponseDescriptionField;

        private string confirmationCodeField;

        private string auditNoField;

        private int topUpAmountField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string TransactionResponseCode
        {
            get
            {
                return this.transactionResponseCodeField;
            }
            set
            {
                this.transactionResponseCodeField = value;
                this.RaisePropertyChanged("TransactionResponseCode");
            }
        }

        /// <remarks/>
        public string TransactionResponseDescription
        {
            get
            {
                return this.transactionResponseDescriptionField;
            }
            set
            {
                this.transactionResponseDescriptionField = value;
                this.RaisePropertyChanged("TransactionResponseDescription");
            }
        }

        /// <remarks/>
        public string ConfirmationCode
        {
            get
            {
                return this.confirmationCodeField;
            }
            set
            {
                this.confirmationCodeField = value;
                this.RaisePropertyChanged("ConfirmationCode");
            }
        }

        /// <remarks/>
        public string AuditNo
        {
            get
            {
                return this.auditNoField;
            }
            set
            {
                this.auditNoField = value;
                this.RaisePropertyChanged("AuditNo");
            }
        }

        /// <remarks/>
        public int TopUpAmount
        {
            get
            {
                return this.topUpAmountField;
            }
            set
            {
                this.topUpAmountField = value;
                this.RaisePropertyChanged("TopUpAmount");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class FlexiTransactionDetail_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string requestIdField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class ResellerBalance_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private int tillDateBalanceField;

        private int currentBalanceField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public int TillDateBalance
        {
            get
            {
                return this.tillDateBalanceField;
            }
            set
            {
                this.tillDateBalanceField = value;
                this.RaisePropertyChanged("TillDateBalance");
            }
        }

        /// <remarks/>
        public int CurrentBalance
        {
            get
            {
                return this.currentBalanceField;
            }
            set
            {
                this.currentBalanceField = value;
                this.RaisePropertyChanged("CurrentBalance");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class ResellerBalance_Request : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string loginIdField;

        private string tillDateField;

        private string checksumField;

        /// <remarks/>
        public string LoginId
        {
            get
            {
                return this.loginIdField;
            }
            set
            {
                this.loginIdField = value;
                this.RaisePropertyChanged("LoginId");
            }
        }

        /// <remarks/>
        public string TillDate
        {
            get
            {
                return this.tillDateField;
            }
            set
            {
                this.tillDateField = value;
                this.RaisePropertyChanged("TillDate");
            }
        }

        /// <remarks/>
        public string Checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
                this.RaisePropertyChanged("Checksum");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace = "http://soapinterop.org/xsd")]
    public partial class EchoCheck_Response : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string responseCodeField;

        private string responseDescriptionField;

        private string messageField;

        /// <remarks/>
        public string ResponseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }

        /// <remarks/>
        public string ResponseDescription
        {
            get
            {
                return this.responseDescriptionField;
            }
            set
            {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EchoCheck", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class EchoCheckRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.EchoCheck_Request EchoCheck_Request;

        public EchoCheckRequest()
        {
        }

        public EchoCheckRequest(Blend.ProvidusImplementation.AirtimeTopup.EchoCheck_Request EchoCheck_Request)
        {
            this.EchoCheck_Request = EchoCheck_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "EchoCheckResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class EchoCheckResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.EchoCheck_Response EchoCheck_Response;

        public EchoCheckResponse()
        {
        }

        public EchoCheckResponse(Blend.ProvidusImplementation.AirtimeTopup.EchoCheck_Response EchoCheck_Response)
        {
            this.EchoCheck_Response = EchoCheck_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResellerBalance", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class ResellerBalanceRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.ResellerBalance_Request ResellerBalance_Request;

        public ResellerBalanceRequest()
        {
        }

        public ResellerBalanceRequest(Blend.ProvidusImplementation.AirtimeTopup.ResellerBalance_Request ResellerBalance_Request)
        {
            this.ResellerBalance_Request = ResellerBalance_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ResellerBalanceResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class ResellerBalanceResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.ResellerBalance_Response ResellerBalance_Response;

        public ResellerBalanceResponse()
        {
        }

        public ResellerBalanceResponse(Blend.ProvidusImplementation.AirtimeTopup.ResellerBalance_Response ResellerBalance_Response)
        {
            this.ResellerBalance_Response = ResellerBalance_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FlexiTransactionDetail", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FlexiTransactionDetailRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetail_Request FlexiTransactionDetail_Request;

        public FlexiTransactionDetailRequest()
        {
        }

        public FlexiTransactionDetailRequest(Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetail_Request FlexiTransactionDetail_Request)
        {
            this.FlexiTransactionDetail_Request = FlexiTransactionDetail_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FlexiTransactionDetailResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FlexiTransactionDetailResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetail_Response FlexiTransactionDetail_Response;

        public FlexiTransactionDetailResponse()
        {
        }

        public FlexiTransactionDetailResponse(Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetail_Response FlexiTransactionDetail_Response)
        {
            this.FlexiTransactionDetail_Response = FlexiTransactionDetail_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FixTransactionDetail", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FixTransactionDetailRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetail_Request FixTransactionDetail_Request;

        public FixTransactionDetailRequest()
        {
        }

        public FixTransactionDetailRequest(Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetail_Request FixTransactionDetail_Request)
        {
            this.FixTransactionDetail_Request = FixTransactionDetail_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FixTransactionDetailResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FixTransactionDetailResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetail_Response FixTransactionDetail_Response;

        public FixTransactionDetailResponse()
        {
        }

        public FixTransactionDetailResponse(Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetail_Response FixTransactionDetail_Response)
        {
            this.FixTransactionDetail_Response = FixTransactionDetail_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FlexiRecharge", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FlexiRechargeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FlexiRecharge_Request FlexiRecharge_Request;

        public FlexiRechargeRequest()
        {
        }

        public FlexiRechargeRequest(Blend.ProvidusImplementation.AirtimeTopup.FlexiRecharge_Request FlexiRecharge_Request)
        {
            this.FlexiRecharge_Request = FlexiRecharge_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FlexiRechargeResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FlexiRechargeResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FlexiRecharge_Response FlexiRecharge_Response;

        public FlexiRechargeResponse()
        {
        }

        public FlexiRechargeResponse(Blend.ProvidusImplementation.AirtimeTopup.FlexiRecharge_Response FlexiRecharge_Response)
        {
            this.FlexiRecharge_Response = FlexiRecharge_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FixRecharge", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FixRechargeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FixRecharge_Request FixRecharge_Request;

        public FixRechargeRequest()
        {
        }

        public FixRechargeRequest(Blend.ProvidusImplementation.AirtimeTopup.FixRecharge_Request FixRecharge_Request)
        {
            this.FixRecharge_Request = FixRecharge_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FixRechargeResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FixRechargeResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FixRecharge_Response FixRecharge_Response;

        public FixRechargeResponse()
        {
        }

        public FixRechargeResponse(Blend.ProvidusImplementation.AirtimeTopup.FixRecharge_Response FixRecharge_Response)
        {
            this.FixRecharge_Response = FixRecharge_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FlexiVoid", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FlexiVoidRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FlexiVoid_Request FlexiVoid_Request;

        public FlexiVoidRequest()
        {
        }

        public FlexiVoidRequest(Blend.ProvidusImplementation.AirtimeTopup.FlexiVoid_Request FlexiVoid_Request)
        {
            this.FlexiVoid_Request = FlexiVoid_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FlexiVoidResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FlexiVoidResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FlexiVoid_Response FlexiVoid_Response;

        public FlexiVoidResponse()
        {
        }

        public FlexiVoidResponse(Blend.ProvidusImplementation.AirtimeTopup.FlexiVoid_Response FlexiVoid_Response)
        {
            this.FlexiVoid_Response = FlexiVoid_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FixVoid", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FixVoidRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FixVoid_Request FixVoid_Request;

        public FixVoidRequest()
        {
        }

        public FixVoidRequest(Blend.ProvidusImplementation.AirtimeTopup.FixVoid_Request FixVoid_Request)
        {
            this.FixVoid_Request = FixVoid_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "FixVoidResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class FixVoidResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.FixVoid_Response FixVoid_Response;

        public FixVoidResponse()
        {
        }

        public FixVoidResponse(Blend.ProvidusImplementation.AirtimeTopup.FixVoid_Response FixVoid_Response)
        {
            this.FixVoid_Response = FixVoid_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "OpenRecharge", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class OpenRechargeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.OpenRecharge_Request OpenRecharge_Request;

        public OpenRechargeRequest()
        {
        }

        public OpenRechargeRequest(Blend.ProvidusImplementation.AirtimeTopup.OpenRecharge_Request OpenRecharge_Request)
        {
            this.OpenRecharge_Request = OpenRecharge_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "OpenRechargeResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class OpenRechargeResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.OpenRecharge_Response OpenRecharge_Response;

        public OpenRechargeResponse()
        {
        }

        public OpenRechargeResponse(Blend.ProvidusImplementation.AirtimeTopup.OpenRecharge_Response OpenRecharge_Response)
        {
            this.OpenRecharge_Response = OpenRecharge_Response;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ActivationDeactivation", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class ActivationDeactivationRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivation_Request ActivationDeactivation_Request;

        public ActivationDeactivationRequest()
        {
        }

        public ActivationDeactivationRequest(Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivation_Request ActivationDeactivation_Request)
        {
            this.ActivationDeactivation_Request = ActivationDeactivation_Request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "ActivationDeactivationResponse", WrapperNamespace = "http://arizonaadmin.mobifinng.com/WebService/reseller_iTopUp/reseller_iTopUp.wsdl" +
        ".php", IsWrapped = true)]
    public partial class ActivationDeactivationResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivation_Response ActivationDeactivation_Response;

        public ActivationDeactivationResponse()
        {
        }

        public ActivationDeactivationResponse(Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivation_Response ActivationDeactivation_Response)
        {
            this.ActivationDeactivation_Response = ActivationDeactivation_Response;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Reseller_iTopUp_wsdlPortChannel : Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Reseller_iTopUp_wsdlPortClient : System.ServiceModel.ClientBase<Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort>, Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort
    {

        public Reseller_iTopUp_wsdlPortClient()
        {
        }

        public Reseller_iTopUp_wsdlPortClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public Reseller_iTopUp_wsdlPortClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public Reseller_iTopUp_wsdlPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public Reseller_iTopUp_wsdlPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.EchoCheckResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.EchoCheck(Blend.ProvidusImplementation.AirtimeTopup.EchoCheckRequest request)
        {
            return base.Channel.EchoCheck(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.EchoCheck_Response EchoCheck(Blend.ProvidusImplementation.AirtimeTopup.EchoCheck_Request EchoCheck_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.EchoCheckRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.EchoCheckRequest();
            inValue.EchoCheck_Request = EchoCheck_Request;
            Blend.ProvidusImplementation.AirtimeTopup.EchoCheckResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).EchoCheck(inValue);
            return retVal.EchoCheck_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.ResellerBalanceResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.ResellerBalance(Blend.ProvidusImplementation.AirtimeTopup.ResellerBalanceRequest request)
        {
            return base.Channel.ResellerBalance(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.ResellerBalance_Response ResellerBalance(Blend.ProvidusImplementation.AirtimeTopup.ResellerBalance_Request ResellerBalance_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.ResellerBalanceRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.ResellerBalanceRequest();
            inValue.ResellerBalance_Request = ResellerBalance_Request;
            Blend.ProvidusImplementation.AirtimeTopup.ResellerBalanceResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).ResellerBalance(inValue);
            return retVal.ResellerBalance_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetailResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.FlexiTransactionDetail(Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetailRequest request)
        {
            return base.Channel.FlexiTransactionDetail(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetail_Response FlexiTransactionDetail(Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetail_Request FlexiTransactionDetail_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetailRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetailRequest();
            inValue.FlexiTransactionDetail_Request = FlexiTransactionDetail_Request;
            Blend.ProvidusImplementation.AirtimeTopup.FlexiTransactionDetailResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).FlexiTransactionDetail(inValue);
            return retVal.FlexiTransactionDetail_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetailResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.FixTransactionDetail(Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetailRequest request)
        {
            return base.Channel.FixTransactionDetail(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetail_Response FixTransactionDetail(Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetail_Request FixTransactionDetail_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetailRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetailRequest();
            inValue.FixTransactionDetail_Request = FixTransactionDetail_Request;
            Blend.ProvidusImplementation.AirtimeTopup.FixTransactionDetailResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).FixTransactionDetail(inValue);
            return retVal.FixTransactionDetail_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.FlexiRechargeResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.FlexiRecharge(Blend.ProvidusImplementation.AirtimeTopup.FlexiRechargeRequest request)
        {
            return base.Channel.FlexiRecharge(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.FlexiRecharge_Response FlexiRecharge(Blend.ProvidusImplementation.AirtimeTopup.FlexiRecharge_Request FlexiRecharge_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.FlexiRechargeRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.FlexiRechargeRequest();
            inValue.FlexiRecharge_Request = FlexiRecharge_Request;
            Blend.ProvidusImplementation.AirtimeTopup.FlexiRechargeResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).FlexiRecharge(inValue);
            return retVal.FlexiRecharge_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.FixRechargeResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.FixRecharge(Blend.ProvidusImplementation.AirtimeTopup.FixRechargeRequest request)
        {
            return base.Channel.FixRecharge(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.FixRecharge_Response FixRecharge(Blend.ProvidusImplementation.AirtimeTopup.FixRecharge_Request FixRecharge_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.FixRechargeRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.FixRechargeRequest();
            inValue.FixRecharge_Request = FixRecharge_Request;
            Blend.ProvidusImplementation.AirtimeTopup.FixRechargeResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).FixRecharge(inValue);
            return retVal.FixRecharge_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.FlexiVoidResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.FlexiVoid(Blend.ProvidusImplementation.AirtimeTopup.FlexiVoidRequest request)
        {
            return base.Channel.FlexiVoid(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.FlexiVoid_Response FlexiVoid(Blend.ProvidusImplementation.AirtimeTopup.FlexiVoid_Request FlexiVoid_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.FlexiVoidRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.FlexiVoidRequest();
            inValue.FlexiVoid_Request = FlexiVoid_Request;
            Blend.ProvidusImplementation.AirtimeTopup.FlexiVoidResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).FlexiVoid(inValue);
            return retVal.FlexiVoid_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.FixVoidResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.FixVoid(Blend.ProvidusImplementation.AirtimeTopup.FixVoidRequest request)
        {
            return base.Channel.FixVoid(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.FixVoid_Response FixVoid(Blend.ProvidusImplementation.AirtimeTopup.FixVoid_Request FixVoid_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.FixVoidRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.FixVoidRequest();
            inValue.FixVoid_Request = FixVoid_Request;
            Blend.ProvidusImplementation.AirtimeTopup.FixVoidResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).FixVoid(inValue);
            return retVal.FixVoid_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.OpenRechargeResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.OpenRecharge(Blend.ProvidusImplementation.AirtimeTopup.OpenRechargeRequest request)
        {
            return base.Channel.OpenRecharge(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.OpenRecharge_Response OpenRecharge(Blend.ProvidusImplementation.AirtimeTopup.OpenRecharge_Request OpenRecharge_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.OpenRechargeRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.OpenRechargeRequest();
            inValue.OpenRecharge_Request = OpenRecharge_Request;
            Blend.ProvidusImplementation.AirtimeTopup.OpenRechargeResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).OpenRecharge(inValue);
            return retVal.OpenRecharge_Response;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivationResponse Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort.ActivationDeactivation(Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivationRequest request)
        {
            return base.Channel.ActivationDeactivation(request);
        }

        public Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivation_Response ActivationDeactivation(Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivation_Request ActivationDeactivation_Request)
        {
            Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivationRequest inValue = new Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivationRequest();
            inValue.ActivationDeactivation_Request = ActivationDeactivation_Request;
            Blend.ProvidusImplementation.AirtimeTopup.ActivationDeactivationResponse retVal = ((Blend.ProvidusImplementation.AirtimeTopup.Reseller_iTopUp_wsdlPort)(this)).ActivationDeactivation(inValue);
            return retVal.ActivationDeactivation_Response;
        }
    }
}
