//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blend.ProvidusImplementation.PNDService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl", ConfigurationName="PNDService.BanksMiddleware_PE04RES00")]
    public interface BanksMiddleware_PE04RES00 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl/e04res10", ReplyAction="*")]
        Blend.ProvidusImplementation.PNDService.e04res10Response e04res10(Blend.ProvidusImplementation.PNDService.e04res10Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl/e04res10", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.PNDService.e04res10Response> e04res10Async(Blend.ProvidusImplementation.PNDService.e04res10Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl/e04res30", ReplyAction="*")]
        Blend.ProvidusImplementation.PNDService.e04res30Response e04res30(Blend.ProvidusImplementation.PNDService.e04res30Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl/e04res30", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.PNDService.e04res30Response> e04res30Async(Blend.ProvidusImplementation.PNDService.e04res30Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e04res10", WrapperNamespace="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl", IsWrapped=true)]
    public partial class e04res10Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal reqLanInd_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public decimal inpChannelId_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string inpChannelRefNum_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public decimal fBraCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public decimal fCusNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public decimal fCurCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public decimal fLedCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public decimal fSubAcctCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public decimal fRestCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string fTextRest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public decimal fAcctRestSeq_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public decimal outRetStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string outReqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public decimal outStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string outMsgTxt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string outDetInfo_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public decimal dbAppErr_out;
        
        public e04res10Request() {
        }
        
        public e04res10Request(
                    decimal reqLanInd_inout, 
                    decimal inpChannelId_inout, 
                    string inpChannelRefNum_inout, 
                    decimal fBraCode, 
                    decimal fCusNum, 
                    decimal fCurCode, 
                    decimal fLedCode, 
                    decimal fSubAcctCode, 
                    decimal fRestCode, 
                    string fTextRest, 
                    decimal fAcctRestSeq_out, 
                    decimal outRetStatus_out, 
                    string outReqId_out, 
                    decimal outStatus_out, 
                    string outMsgTxt_out, 
                    string outDetInfo_out, 
                    decimal dbAppErr_out) {
            this.reqLanInd_inout = reqLanInd_inout;
            this.inpChannelId_inout = inpChannelId_inout;
            this.inpChannelRefNum_inout = inpChannelRefNum_inout;
            this.fBraCode = fBraCode;
            this.fCusNum = fCusNum;
            this.fCurCode = fCurCode;
            this.fLedCode = fLedCode;
            this.fSubAcctCode = fSubAcctCode;
            this.fRestCode = fRestCode;
            this.fTextRest = fTextRest;
            this.fAcctRestSeq_out = fAcctRestSeq_out;
            this.outRetStatus_out = outRetStatus_out;
            this.outReqId_out = outReqId_out;
            this.outStatus_out = outStatus_out;
            this.outMsgTxt_out = outMsgTxt_out;
            this.outDetInfo_out = outDetInfo_out;
            this.dbAppErr_out = dbAppErr_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e04res10Response", WrapperNamespace="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl", IsWrapped=true)]
    public partial class e04res10Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal reqLanInd_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public decimal inpChannelId_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string inpChannelRefNum_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public decimal fAcctRestSeq_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public decimal outRetStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string outReqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public decimal outStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string outMsgTxt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string outDetInfo_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public decimal dbAppErr_out;
        
        public e04res10Response() {
        }
        
        public e04res10Response(decimal reqLanInd_inout, decimal inpChannelId_inout, string inpChannelRefNum_inout, decimal fAcctRestSeq_out, decimal outRetStatus_out, string outReqId_out, decimal outStatus_out, string outMsgTxt_out, string outDetInfo_out, decimal dbAppErr_out) {
            this.reqLanInd_inout = reqLanInd_inout;
            this.inpChannelId_inout = inpChannelId_inout;
            this.inpChannelRefNum_inout = inpChannelRefNum_inout;
            this.fAcctRestSeq_out = fAcctRestSeq_out;
            this.outRetStatus_out = outRetStatus_out;
            this.outReqId_out = outReqId_out;
            this.outStatus_out = outStatus_out;
            this.outMsgTxt_out = outMsgTxt_out;
            this.outDetInfo_out = outDetInfo_out;
            this.dbAppErr_out = dbAppErr_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e04res30", WrapperNamespace="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl", IsWrapped=true)]
    public partial class e04res30Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal reqLanInd_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public decimal inpChannelId_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string inpChannelRefNum_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public decimal fBraCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public decimal fCusNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public decimal fCurCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public decimal fLedCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public decimal fSubAcctCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public decimal fAcctRestSeq;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public decimal outRetStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string outReqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public decimal outStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string outMsgTxt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string outDetInfo_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public decimal dbAppErr_out;
        
        public e04res30Request() {
        }
        
        public e04res30Request(decimal reqLanInd_inout, decimal inpChannelId_inout, string inpChannelRefNum_inout, decimal fBraCode, decimal fCusNum, decimal fCurCode, decimal fLedCode, decimal fSubAcctCode, decimal fAcctRestSeq, decimal outRetStatus_out, string outReqId_out, decimal outStatus_out, string outMsgTxt_out, string outDetInfo_out, decimal dbAppErr_out) {
            this.reqLanInd_inout = reqLanInd_inout;
            this.inpChannelId_inout = inpChannelId_inout;
            this.inpChannelRefNum_inout = inpChannelRefNum_inout;
            this.fBraCode = fBraCode;
            this.fCusNum = fCusNum;
            this.fCurCode = fCurCode;
            this.fLedCode = fLedCode;
            this.fSubAcctCode = fSubAcctCode;
            this.fAcctRestSeq = fAcctRestSeq;
            this.outRetStatus_out = outRetStatus_out;
            this.outReqId_out = outReqId_out;
            this.outStatus_out = outStatus_out;
            this.outMsgTxt_out = outMsgTxt_out;
            this.outDetInfo_out = outDetInfo_out;
            this.dbAppErr_out = dbAppErr_out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="e04res30Response", WrapperNamespace="http://com/icsfs/banks/ws/BanksMiddleware_PE04RES00.wsdl", IsWrapped=true)]
    public partial class e04res30Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public decimal reqLanInd_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public decimal inpChannelId_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string inpChannelRefNum_inout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public decimal outRetStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string outReqId_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public decimal outStatus_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string outMsgTxt_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string outDetInfo_out;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public decimal dbAppErr_out;
        
        public e04res30Response() {
        }
        
        public e04res30Response(decimal reqLanInd_inout, decimal inpChannelId_inout, string inpChannelRefNum_inout, decimal outRetStatus_out, string outReqId_out, decimal outStatus_out, string outMsgTxt_out, string outDetInfo_out, decimal dbAppErr_out) {
            this.reqLanInd_inout = reqLanInd_inout;
            this.inpChannelId_inout = inpChannelId_inout;
            this.inpChannelRefNum_inout = inpChannelRefNum_inout;
            this.outRetStatus_out = outRetStatus_out;
            this.outReqId_out = outReqId_out;
            this.outStatus_out = outStatus_out;
            this.outMsgTxt_out = outMsgTxt_out;
            this.outDetInfo_out = outDetInfo_out;
            this.dbAppErr_out = dbAppErr_out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BanksMiddleware_PE04RES00Channel : Blend.ProvidusImplementation.PNDService.BanksMiddleware_PE04RES00, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BanksMiddleware_PE04RES00Client : System.ServiceModel.ClientBase<Blend.ProvidusImplementation.PNDService.BanksMiddleware_PE04RES00>, Blend.ProvidusImplementation.PNDService.BanksMiddleware_PE04RES00 {
        
        public BanksMiddleware_PE04RES00Client() {
        }
        
        public BanksMiddleware_PE04RES00Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BanksMiddleware_PE04RES00Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanksMiddleware_PE04RES00Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BanksMiddleware_PE04RES00Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.PNDService.e04res10Response Blend.ProvidusImplementation.PNDService.BanksMiddleware_PE04RES00.e04res10(Blend.ProvidusImplementation.PNDService.e04res10Request request) {
            return base.Channel.e04res10(request);
        }
        
        public void e04res10(
                    ref decimal reqLanInd_inout, 
                    ref decimal inpChannelId_inout, 
                    ref string inpChannelRefNum_inout, 
                    decimal fBraCode, 
                    decimal fCusNum, 
                    decimal fCurCode, 
                    decimal fLedCode, 
                    decimal fSubAcctCode, 
                    decimal fRestCode, 
                    string fTextRest, 
                    ref decimal fAcctRestSeq_out, 
                    ref decimal outRetStatus_out, 
                    ref string outReqId_out, 
                    ref decimal outStatus_out, 
                    ref string outMsgTxt_out, 
                    ref string outDetInfo_out, 
                    ref decimal dbAppErr_out) {
            Blend.ProvidusImplementation.PNDService.e04res10Request inValue = new Blend.ProvidusImplementation.PNDService.e04res10Request();
            inValue.reqLanInd_inout = reqLanInd_inout;
            inValue.inpChannelId_inout = inpChannelId_inout;
            inValue.inpChannelRefNum_inout = inpChannelRefNum_inout;
            inValue.fBraCode = fBraCode;
            inValue.fCusNum = fCusNum;
            inValue.fCurCode = fCurCode;
            inValue.fLedCode = fLedCode;
            inValue.fSubAcctCode = fSubAcctCode;
            inValue.fRestCode = fRestCode;
            inValue.fTextRest = fTextRest;
            inValue.fAcctRestSeq_out = fAcctRestSeq_out;
            inValue.outRetStatus_out = outRetStatus_out;
            inValue.outReqId_out = outReqId_out;
            inValue.outStatus_out = outStatus_out;
            inValue.outMsgTxt_out = outMsgTxt_out;
            inValue.outDetInfo_out = outDetInfo_out;
            inValue.dbAppErr_out = dbAppErr_out;
            Blend.ProvidusImplementation.PNDService.e04res10Response retVal = ((Blend.ProvidusImplementation.PNDService.BanksMiddleware_PE04RES00)(this)).e04res10(inValue);
            reqLanInd_inout = retVal.reqLanInd_inout;
            inpChannelId_inout = retVal.inpChannelId_inout;
            inpChannelRefNum_inout = retVal.inpChannelRefNum_inout;
            fAcctRestSeq_out = retVal.fAcctRestSeq_out;
            outRetStatus_out = retVal.outRetStatus_out;
            outReqId_out = retVal.outReqId_out;
            outStatus_out = retVal.outStatus_out;
            outMsgTxt_out = retVal.outMsgTxt_out;
            outDetInfo_out = retVal.outDetInfo_out;
            dbAppErr_out = retVal.dbAppErr_out;
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.PNDService.e04res10Response> e04res10Async(Blend.ProvidusImplementation.PNDService.e04res10Request request) {
            return base.Channel.e04res10Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.PNDService.e04res30Response Blend.ProvidusImplementation.PNDService.BanksMiddleware_PE04RES00.e04res30(Blend.ProvidusImplementation.PNDService.e04res30Request request) {
            return base.Channel.e04res30(request);
        }
        
        public void e04res30(ref decimal reqLanInd_inout, ref decimal inpChannelId_inout, ref string inpChannelRefNum_inout, decimal fBraCode, decimal fCusNum, decimal fCurCode, decimal fLedCode, decimal fSubAcctCode, decimal fAcctRestSeq, ref decimal outRetStatus_out, ref string outReqId_out, ref decimal outStatus_out, ref string outMsgTxt_out, ref string outDetInfo_out, ref decimal dbAppErr_out) {
            Blend.ProvidusImplementation.PNDService.e04res30Request inValue = new Blend.ProvidusImplementation.PNDService.e04res30Request();
            inValue.reqLanInd_inout = reqLanInd_inout;
            inValue.inpChannelId_inout = inpChannelId_inout;
            inValue.inpChannelRefNum_inout = inpChannelRefNum_inout;
            inValue.fBraCode = fBraCode;
            inValue.fCusNum = fCusNum;
            inValue.fCurCode = fCurCode;
            inValue.fLedCode = fLedCode;
            inValue.fSubAcctCode = fSubAcctCode;
            inValue.fAcctRestSeq = fAcctRestSeq;
            inValue.outRetStatus_out = outRetStatus_out;
            inValue.outReqId_out = outReqId_out;
            inValue.outStatus_out = outStatus_out;
            inValue.outMsgTxt_out = outMsgTxt_out;
            inValue.outDetInfo_out = outDetInfo_out;
            inValue.dbAppErr_out = dbAppErr_out;
            Blend.ProvidusImplementation.PNDService.e04res30Response retVal = ((Blend.ProvidusImplementation.PNDService.BanksMiddleware_PE04RES00)(this)).e04res30(inValue);
            reqLanInd_inout = retVal.reqLanInd_inout;
            inpChannelId_inout = retVal.inpChannelId_inout;
            inpChannelRefNum_inout = retVal.inpChannelRefNum_inout;
            outRetStatus_out = retVal.outRetStatus_out;
            outReqId_out = retVal.outReqId_out;
            outStatus_out = retVal.outStatus_out;
            outMsgTxt_out = retVal.outMsgTxt_out;
            outDetInfo_out = retVal.outDetInfo_out;
            dbAppErr_out = retVal.dbAppErr_out;
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.PNDService.e04res30Response> e04res30Async(Blend.ProvidusImplementation.PNDService.e04res30Request request) {
            return base.Channel.e04res30Async(request);
        }
    }
}
