//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blend.ProvidusImplementation.NIPBVNService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://providus.com/", ConfigurationName="NIPBVNService.Validator")]
    public interface Validator {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getMiddleNameRequest", ReplyAction="http://providus.com/Validator/getMiddleNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getMiddleNameResponse getMiddleName(Blend.ProvidusImplementation.NIPBVNService.getMiddleNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getDOBRequest", ReplyAction="http://providus.com/Validator/getDOBResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getDOBResponse getDOB(Blend.ProvidusImplementation.NIPBVNService.getDOBRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getFirstNameRequest", ReplyAction="http://providus.com/Validator/getFirstNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getFirstNameResponse getFirstName(Blend.ProvidusImplementation.NIPBVNService.getFirstNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getPhoneRequest", ReplyAction="http://providus.com/Validator/getPhoneResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getPhoneResponse getPhone(Blend.ProvidusImplementation.NIPBVNService.getPhoneRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/encryptRequestRequest", ReplyAction="http://providus.com/Validator/encryptRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.encryptRequestResponse encryptRequest(Blend.ProvidusImplementation.NIPBVNService.encryptRequestRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getAllRequest", ReplyAction="http://providus.com/Validator/getAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getAllResponse getAll(Blend.ProvidusImplementation.NIPBVNService.getAllRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getBVNRequest", ReplyAction="http://providus.com/Validator/getBVNResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getBVNResponse getBVN(Blend.ProvidusImplementation.NIPBVNService.getBVNRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/betweenRequest", ReplyAction="http://providus.com/Validator/betweenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.betweenResponse between(Blend.ProvidusImplementation.NIPBVNService.betweenRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getStatusRequest", ReplyAction="http://providus.com/Validator/getStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getStatusResponse getStatus(Blend.ProvidusImplementation.NIPBVNService.getStatusRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/decryptRequestRequest", ReplyAction="http://providus.com/Validator/decryptRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.decryptRequestResponse decryptRequest(Blend.ProvidusImplementation.NIPBVNService.decryptRequestRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/verifyBVNRequest", ReplyAction="http://providus.com/Validator/verifyBVNResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.verifyBVNResponse verifyBVN(Blend.ProvidusImplementation.NIPBVNService.verifyBVNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/generatePublicAndPrivateKeysRequest", ReplyAction="http://providus.com/Validator/generatePublicAndPrivateKeysResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void generatePublicAndPrivateKeys();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://providus.com/Validator/getSurnameRequest", ReplyAction="http://providus.com/Validator/getSurnameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Blend.ProvidusImplementation.NIPBVNService.getSurnameResponse getSurname(Blend.ProvidusImplementation.NIPBVNService.getSurnameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMiddleName", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getMiddleNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getMiddleNameRequest() {
        }
        
        public getMiddleNameRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMiddleNameResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getMiddleNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getMiddleNameResponse() {
        }
        
        public getMiddleNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDOB", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getDOBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getDOBRequest() {
        }
        
        public getDOBRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDOBResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getDOBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getDOBResponse() {
        }
        
        public getDOBResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFirstName", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getFirstNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getFirstNameRequest() {
        }
        
        public getFirstNameRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFirstNameResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getFirstNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getFirstNameResponse() {
        }
        
        public getFirstNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPhone", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getPhoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPhoneRequest() {
        }
        
        public getPhoneRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPhoneResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getPhoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getPhoneResponse() {
        }
        
        public getPhoneResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="encryptRequest", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class encryptRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public encryptRequestRequest() {
        }
        
        public encryptRequestRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="encryptRequestResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class encryptRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public encryptRequestResponse() {
        }
        
        public encryptRequestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAll", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getAllRequest() {
        }
        
        public getAllRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getAllResponse() {
        }
        
        public getAllResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBVN", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getBVNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getBVNRequest() {
        }
        
        public getBVNRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBVNResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getBVNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getBVNResponse() {
        }
        
        public getBVNResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="between", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class betweenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public betweenRequest() {
        }
        
        public betweenRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="betweenResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class betweenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public betweenResponse() {
        }
        
        public betweenResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatus", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getStatusRequest() {
        }
        
        public getStatusRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getStatusResponse() {
        }
        
        public getStatusResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="decryptRequest", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class decryptRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public decryptRequestRequest() {
        }
        
        public decryptRequestRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="decryptRequestResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class decryptRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public decryptRequestResponse() {
        }
        
        public decryptRequestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyBVN", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class verifyBVNRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public verifyBVNRequest() {
        }
        
        public verifyBVNRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verifyBVNResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class verifyBVNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public verifyBVNResponse() {
        }
        
        public verifyBVNResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSurname", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getSurnameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getSurnameRequest() {
        }
        
        public getSurnameRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSurnameResponse", WrapperNamespace="http://providus.com/", IsWrapped=true)]
    public partial class getSurnameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://providus.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getSurnameResponse() {
        }
        
        public getSurnameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidatorChannel : Blend.ProvidusImplementation.NIPBVNService.Validator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidatorClient : System.ServiceModel.ClientBase<Blend.ProvidusImplementation.NIPBVNService.Validator>, Blend.ProvidusImplementation.NIPBVNService.Validator {
        
        public ValidatorClient() {
        }
        
        public ValidatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getMiddleNameResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getMiddleName(Blend.ProvidusImplementation.NIPBVNService.getMiddleNameRequest request) {
            return base.Channel.getMiddleName(request);
        }
        
        public string getMiddleName(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getMiddleNameRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getMiddleNameRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getMiddleNameResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getMiddleName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getDOBResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getDOB(Blend.ProvidusImplementation.NIPBVNService.getDOBRequest request) {
            return base.Channel.getDOB(request);
        }
        
        public string getDOB(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getDOBRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getDOBRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getDOBResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getDOB(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getFirstNameResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getFirstName(Blend.ProvidusImplementation.NIPBVNService.getFirstNameRequest request) {
            return base.Channel.getFirstName(request);
        }
        
        public string getFirstName(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getFirstNameRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getFirstNameRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getFirstNameResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getFirstName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getPhoneResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getPhone(Blend.ProvidusImplementation.NIPBVNService.getPhoneRequest request) {
            return base.Channel.getPhone(request);
        }
        
        public string getPhone(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getPhoneRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getPhoneRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getPhoneResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getPhone(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.encryptRequestResponse Blend.ProvidusImplementation.NIPBVNService.Validator.encryptRequest(Blend.ProvidusImplementation.NIPBVNService.encryptRequestRequest request) {
            return base.Channel.encryptRequest(request);
        }
        
        public string encryptRequest(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.encryptRequestRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.encryptRequestRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.encryptRequestResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).encryptRequest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getAllResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getAll(Blend.ProvidusImplementation.NIPBVNService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public string[] getAll(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getAllRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getAllRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getAllResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getBVNResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getBVN(Blend.ProvidusImplementation.NIPBVNService.getBVNRequest request) {
            return base.Channel.getBVN(request);
        }
        
        public string getBVN(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getBVNRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getBVNRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getBVNResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getBVN(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.betweenResponse Blend.ProvidusImplementation.NIPBVNService.Validator.between(Blend.ProvidusImplementation.NIPBVNService.betweenRequest request) {
            return base.Channel.between(request);
        }
        
        public string between(string arg0, string arg1, string arg2) {
            Blend.ProvidusImplementation.NIPBVNService.betweenRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.betweenRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Blend.ProvidusImplementation.NIPBVNService.betweenResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).between(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getStatusResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getStatus(Blend.ProvidusImplementation.NIPBVNService.getStatusRequest request) {
            return base.Channel.getStatus(request);
        }
        
        public string getStatus(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getStatusRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getStatusRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getStatusResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.decryptRequestResponse Blend.ProvidusImplementation.NIPBVNService.Validator.decryptRequest(Blend.ProvidusImplementation.NIPBVNService.decryptRequestRequest request) {
            return base.Channel.decryptRequest(request);
        }
        
        public string decryptRequest(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.decryptRequestRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.decryptRequestRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.decryptRequestResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).decryptRequest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.verifyBVNResponse Blend.ProvidusImplementation.NIPBVNService.Validator.verifyBVN(Blend.ProvidusImplementation.NIPBVNService.verifyBVNRequest request) {
            return base.Channel.verifyBVN(request);
        }
        
        public string verifyBVN(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.verifyBVNRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.verifyBVNRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.verifyBVNResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).verifyBVN(inValue);
            return retVal.@return;
        }
        
        public void generatePublicAndPrivateKeys() {
            base.Channel.generatePublicAndPrivateKeys();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NIPBVNService.getSurnameResponse Blend.ProvidusImplementation.NIPBVNService.Validator.getSurname(Blend.ProvidusImplementation.NIPBVNService.getSurnameRequest request) {
            return base.Channel.getSurname(request);
        }
        
        public string getSurname(string arg0) {
            Blend.ProvidusImplementation.NIPBVNService.getSurnameRequest inValue = new Blend.ProvidusImplementation.NIPBVNService.getSurnameRequest();
            inValue.arg0 = arg0;
            Blend.ProvidusImplementation.NIPBVNService.getSurnameResponse retVal = ((Blend.ProvidusImplementation.NIPBVNService.Validator)(this)).getSurname(inValue);
            return retVal.@return;
        }
    }
}
