//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blend.ProvidusImplementation.OpenAccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://providus.com/", ConfigurationName="OpenAccountService.IAccount")]
    public interface IAccount {
        
        // CODEGEN: Generating message contract since element name ref_num from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Blend.ProvidusImplementation.OpenAccountService.addAccountResponse addAccount(Blend.ProvidusImplementation.OpenAccountService.addAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.OpenAccountService.addAccountResponse> addAccountAsync(Blend.ProvidusImplementation.OpenAccountService.addAccountRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Blend.ProvidusImplementation.OpenAccountService.getBranchesResponse getBranches(Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.OpenAccountService.getBranchesResponse> getBranchesAsync(Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAccount", Namespace="http://providus.com/", Order=0)]
        public Blend.ProvidusImplementation.OpenAccountService.addAccountRequestBody Body;
        
        public addAccountRequest() {
        }
        
        public addAccountRequest(Blend.ProvidusImplementation.OpenAccountService.addAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ref_num;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bvn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobile_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bra_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int account_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string first_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string account_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string address_line1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string address_line2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string id_image_url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string photo_image_url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string date_of_birth;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string gender;
        
        public addAccountRequestBody() {
        }
        
        public addAccountRequestBody(string ref_num, string bvn, string mobile_no, string email, string bra_code, int account_type, string surname, string first_name, string account_name, string address_line1, string address_line2, string id_image_url, string photo_image_url, string date_of_birth, string gender) {
            this.ref_num = ref_num;
            this.bvn = bvn;
            this.mobile_no = mobile_no;
            this.email = email;
            this.bra_code = bra_code;
            this.account_type = account_type;
            this.surname = surname;
            this.first_name = first_name;
            this.account_name = account_name;
            this.address_line1 = address_line1;
            this.address_line2 = address_line2;
            this.id_image_url = id_image_url;
            this.photo_image_url = photo_image_url;
            this.date_of_birth = date_of_birth;
            this.gender = gender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAccountResponse", Namespace="http://providus.com/", Order=0)]
        public Blend.ProvidusImplementation.OpenAccountService.addAccountResponseBody Body;
        
        public addAccountResponse() {
        }
        
        public addAccountResponse(Blend.ProvidusImplementation.OpenAccountService.addAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public addAccountResponseBody() {
        }
        
        public addAccountResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBranchesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBranches", Namespace="http://providus.com/", Order=0)]
        public Blend.ProvidusImplementation.OpenAccountService.getBranchesRequestBody Body;
        
        public getBranchesRequest() {
        }
        
        public getBranchesRequest(Blend.ProvidusImplementation.OpenAccountService.getBranchesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getBranchesRequestBody {
        
        public getBranchesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBranchesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBranchesResponse", Namespace="http://providus.com/", Order=0)]
        public Blend.ProvidusImplementation.OpenAccountService.getBranchesResponseBody Body;
        
        public getBranchesResponse() {
        }
        
        public getBranchesResponse(Blend.ProvidusImplementation.OpenAccountService.getBranchesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getBranchesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getBranchesResponseBody() {
        }
        
        public getBranchesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountChannel : Blend.ProvidusImplementation.OpenAccountService.IAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountClient : System.ServiceModel.ClientBase<Blend.ProvidusImplementation.OpenAccountService.IAccount>, Blend.ProvidusImplementation.OpenAccountService.IAccount {
        
        public AccountClient() {
        }
        
        public AccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.OpenAccountService.addAccountResponse Blend.ProvidusImplementation.OpenAccountService.IAccount.addAccount(Blend.ProvidusImplementation.OpenAccountService.addAccountRequest request) {
            return base.Channel.addAccount(request);
        }
        
        public string addAccount(string ref_num, string bvn, string mobile_no, string email, string bra_code, int account_type, string surname, string first_name, string account_name, string address_line1, string address_line2, string id_image_url, string photo_image_url, string date_of_birth, string gender) {
            Blend.ProvidusImplementation.OpenAccountService.addAccountRequest inValue = new Blend.ProvidusImplementation.OpenAccountService.addAccountRequest();
            inValue.Body = new Blend.ProvidusImplementation.OpenAccountService.addAccountRequestBody();
            inValue.Body.ref_num = ref_num;
            inValue.Body.bvn = bvn;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.email = email;
            inValue.Body.bra_code = bra_code;
            inValue.Body.account_type = account_type;
            inValue.Body.surname = surname;
            inValue.Body.first_name = first_name;
            inValue.Body.account_name = account_name;
            inValue.Body.address_line1 = address_line1;
            inValue.Body.address_line2 = address_line2;
            inValue.Body.id_image_url = id_image_url;
            inValue.Body.photo_image_url = photo_image_url;
            inValue.Body.date_of_birth = date_of_birth;
            inValue.Body.gender = gender;
            Blend.ProvidusImplementation.OpenAccountService.addAccountResponse retVal = ((Blend.ProvidusImplementation.OpenAccountService.IAccount)(this)).addAccount(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.OpenAccountService.addAccountResponse> Blend.ProvidusImplementation.OpenAccountService.IAccount.addAccountAsync(Blend.ProvidusImplementation.OpenAccountService.addAccountRequest request) {
            return base.Channel.addAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.OpenAccountService.addAccountResponse> addAccountAsync(string ref_num, string bvn, string mobile_no, string email, string bra_code, int account_type, string surname, string first_name, string account_name, string address_line1, string address_line2, string id_image_url, string photo_image_url, string date_of_birth, string gender) {
            Blend.ProvidusImplementation.OpenAccountService.addAccountRequest inValue = new Blend.ProvidusImplementation.OpenAccountService.addAccountRequest();
            inValue.Body = new Blend.ProvidusImplementation.OpenAccountService.addAccountRequestBody();
            inValue.Body.ref_num = ref_num;
            inValue.Body.bvn = bvn;
            inValue.Body.mobile_no = mobile_no;
            inValue.Body.email = email;
            inValue.Body.bra_code = bra_code;
            inValue.Body.account_type = account_type;
            inValue.Body.surname = surname;
            inValue.Body.first_name = first_name;
            inValue.Body.account_name = account_name;
            inValue.Body.address_line1 = address_line1;
            inValue.Body.address_line2 = address_line2;
            inValue.Body.id_image_url = id_image_url;
            inValue.Body.photo_image_url = photo_image_url;
            inValue.Body.date_of_birth = date_of_birth;
            inValue.Body.gender = gender;
            return ((Blend.ProvidusImplementation.OpenAccountService.IAccount)(this)).addAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.OpenAccountService.getBranchesResponse Blend.ProvidusImplementation.OpenAccountService.IAccount.getBranches(Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest request) {
            return base.Channel.getBranches(request);
        }
        
        public string getBranches() {
            Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest inValue = new Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest();
            inValue.Body = new Blend.ProvidusImplementation.OpenAccountService.getBranchesRequestBody();
            Blend.ProvidusImplementation.OpenAccountService.getBranchesResponse retVal = ((Blend.ProvidusImplementation.OpenAccountService.IAccount)(this)).getBranches(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.OpenAccountService.getBranchesResponse> Blend.ProvidusImplementation.OpenAccountService.IAccount.getBranchesAsync(Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest request) {
            return base.Channel.getBranchesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.OpenAccountService.getBranchesResponse> getBranchesAsync() {
            Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest inValue = new Blend.ProvidusImplementation.OpenAccountService.getBranchesRequest();
            inValue.Body = new Blend.ProvidusImplementation.OpenAccountService.getBranchesRequestBody();
            return ((Blend.ProvidusImplementation.OpenAccountService.IAccount)(this)).getBranchesAsync(inValue);
        }
    }
}
