//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blend.ProvidusImplementation.NFPOutwardService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NFPOutwardService.NFPOutwardService_BranchSoap")]
    public interface NFPOutwardService_BranchSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txnstatusquerysingleitem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleResponse txnstatusquerysingleitem(Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleRequest o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/txnstatusquerysingleitem", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleResponse> txnstatusquerysingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleRequest o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerCummulativeAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCustomerCummulativeAmount(string myCustomerSourceAccountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomerCummulativeAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCustomerCummulativeAmountAsync(string myCustomerSourceAccountNumber);
        
        // CODEGEN: Generating message contract since message BranchNameEnquirySingleitemRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchNameEnquirySingleitem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemResponse BranchNameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchNameEnquirySingleitem", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemResponse> BranchNameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest request);
        
        // CODEGEN: Generating message contract since message BranchFundtransfersingleitem_dcRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchFundtransfersingleitem_dc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcResponse BranchFundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BranchFundtransfersingleitem_dc", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcResponse> BranchFundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest request);
        
        // CODEGEN: Generating message contract since message RIB_NameEnquirySingleitemRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RIB_NameEnquirySingleitem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemResponse RIB_NameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RIB_NameEnquirySingleitem", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemResponse> RIB_NameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest request);
        
        // CODEGEN: Generating message contract since message RIB_Fundtransfersingleitem_dcRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RIB_Fundtransfersingleitem_dc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcResponse RIB_Fundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RIB_Fundtransfersingleitem_dc", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcResponse> RIB_Fundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest request);
        
        // CODEGEN: Generating message contract since message CIB_NameEnquirySingleitemRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIB_NameEnquirySingleitem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemResponse CIB_NameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIB_NameEnquirySingleitem", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemResponse> CIB_NameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest request);
        
        // CODEGEN: Generating message contract since message CIB_Fundtransfersingleitem_dcRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIB_Fundtransfersingleitem_dc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcResponse CIB_Fundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIB_Fundtransfersingleitem_dc", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcResponse> CIB_Fundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest request);
        
        // CODEGEN: Generating message contract since message EbillsFundtransfersingleitem_dcRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EbillsFundtransfersingleitem_dc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcResponse EbillsFundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EbillsFundtransfersingleitem_dc", ReplyAction="*")]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcResponse> EbillsFundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNIBSSCharges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double GetNIBSSCharges(double myAmountCharge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNIBSSCharges", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GetNIBSSChargesAsync(double myAmountCharge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNFPBanks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetNFPBanks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNFPBanks", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetNFPBanksAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TSQuerySingleRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private string sourceInstitutionCodeField;
        
        private string channelCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SourceInstitutionCode {
            get {
                return this.sourceInstitutionCodeField;
            }
            set {
                this.sourceInstitutionCodeField = value;
                this.RaisePropertyChanged("SourceInstitutionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ChannelCode {
            get {
                return this.channelCodeField;
            }
            set {
                this.channelCodeField = value;
                this.RaisePropertyChanged("ChannelCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TSQuerySingleResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIDField;
        
        private string sourceInstitutionCodeField;
        
        private int channelCodeField;
        
        private string responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("SessionID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SourceInstitutionCode {
            get {
                return this.sourceInstitutionCodeField;
            }
            set {
                this.sourceInstitutionCodeField = value;
                this.RaisePropertyChanged("SourceInstitutionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ChannelCode {
            get {
                return this.channelCodeField;
            }
            set {
                this.channelCodeField = value;
                this.RaisePropertyChanged("ChannelCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BranchNameEnquirySingleitem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BranchNameEnquirySingleitemRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myDestinationBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myChannelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string mySourceAccountNumber;
        
        public BranchNameEnquirySingleitemRequest() {
        }
        
        public BranchNameEnquirySingleitemRequest(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            this.AuthHeader = AuthHeader;
            this.myDestinationBankCode = myDestinationBankCode;
            this.myAccountNumber = myAccountNumber;
            this.myChannelCode = myChannelCode;
            this.mySourceAccountNumber = mySourceAccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BranchNameEnquirySingleitemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BranchNameEnquirySingleitemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BranchNameEnquirySingleitemResult;
        
        public BranchNameEnquirySingleitemResponse() {
        }
        
        public BranchNameEnquirySingleitemResponse(string BranchNameEnquirySingleitemResult) {
            this.BranchNameEnquirySingleitemResult = BranchNameEnquirySingleitemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BranchFundtransfersingleitem_dc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BranchFundtransfersingleitem_dcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myDestinationBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myChannelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myCustDestinationAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string myAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string myOriginatorName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string myNarration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string myPaymentReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string myAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string myCustomerSourceAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int TranType;
        
        public BranchFundtransfersingleitem_dcRequest() {
        }
        
        public BranchFundtransfersingleitem_dcRequest(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber, int TranType) {
            this.AuthHeader = AuthHeader;
            this.myDestinationBankCode = myDestinationBankCode;
            this.myChannelCode = myChannelCode;
            this.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            this.myAccountName = myAccountName;
            this.myOriginatorName = myOriginatorName;
            this.myNarration = myNarration;
            this.myPaymentReference = myPaymentReference;
            this.myAmount = myAmount;
            this.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            this.TranType = TranType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BranchFundtransfersingleitem_dcResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class BranchFundtransfersingleitem_dcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string BranchFundtransfersingleitem_dcResult;
        
        public BranchFundtransfersingleitem_dcResponse() {
        }
        
        public BranchFundtransfersingleitem_dcResponse(string BranchFundtransfersingleitem_dcResult) {
            this.BranchFundtransfersingleitem_dcResult = BranchFundtransfersingleitem_dcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RIB_NameEnquirySingleitem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RIB_NameEnquirySingleitemRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myDestinationBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myChannelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string mySourceAccountNumber;
        
        public RIB_NameEnquirySingleitemRequest() {
        }
        
        public RIB_NameEnquirySingleitemRequest(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            this.AuthHeader = AuthHeader;
            this.myDestinationBankCode = myDestinationBankCode;
            this.myAccountNumber = myAccountNumber;
            this.myChannelCode = myChannelCode;
            this.mySourceAccountNumber = mySourceAccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RIB_NameEnquirySingleitemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RIB_NameEnquirySingleitemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RIB_NameEnquirySingleitemResult;
        
        public RIB_NameEnquirySingleitemResponse() {
        }
        
        public RIB_NameEnquirySingleitemResponse(string RIB_NameEnquirySingleitemResult) {
            this.RIB_NameEnquirySingleitemResult = RIB_NameEnquirySingleitemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RIB_Fundtransfersingleitem_dc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RIB_Fundtransfersingleitem_dcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myDestinationBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myChannelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myCustDestinationAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string myAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string myOriginatorName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string myNarration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string myPaymentReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string myAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string myCustomerSourceAccountNumber;
        
        public RIB_Fundtransfersingleitem_dcRequest() {
        }
        
        public RIB_Fundtransfersingleitem_dcRequest(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            this.AuthHeader = AuthHeader;
            this.myDestinationBankCode = myDestinationBankCode;
            this.myChannelCode = myChannelCode;
            this.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            this.myAccountName = myAccountName;
            this.myOriginatorName = myOriginatorName;
            this.myNarration = myNarration;
            this.myPaymentReference = myPaymentReference;
            this.myAmount = myAmount;
            this.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RIB_Fundtransfersingleitem_dcResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RIB_Fundtransfersingleitem_dcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RIB_Fundtransfersingleitem_dcResult;
        
        public RIB_Fundtransfersingleitem_dcResponse() {
        }
        
        public RIB_Fundtransfersingleitem_dcResponse(string RIB_Fundtransfersingleitem_dcResult) {
            this.RIB_Fundtransfersingleitem_dcResult = RIB_Fundtransfersingleitem_dcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIB_NameEnquirySingleitem", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CIB_NameEnquirySingleitemRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myDestinationBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myChannelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string mySourceAccountNumber;
        
        public CIB_NameEnquirySingleitemRequest() {
        }
        
        public CIB_NameEnquirySingleitemRequest(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            this.AuthHeader = AuthHeader;
            this.myDestinationBankCode = myDestinationBankCode;
            this.myAccountNumber = myAccountNumber;
            this.myChannelCode = myChannelCode;
            this.mySourceAccountNumber = mySourceAccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIB_NameEnquirySingleitemResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CIB_NameEnquirySingleitemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CIB_NameEnquirySingleitemResult;
        
        public CIB_NameEnquirySingleitemResponse() {
        }
        
        public CIB_NameEnquirySingleitemResponse(string CIB_NameEnquirySingleitemResult) {
            this.CIB_NameEnquirySingleitemResult = CIB_NameEnquirySingleitemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIB_Fundtransfersingleitem_dc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CIB_Fundtransfersingleitem_dcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myDestinationBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myChannelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myCustDestinationAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string myAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string myOriginatorName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string myNarration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string myPaymentReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string myAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string myCustomerSourceAccountNumber;
        
        public CIB_Fundtransfersingleitem_dcRequest() {
        }
        
        public CIB_Fundtransfersingleitem_dcRequest(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            this.AuthHeader = AuthHeader;
            this.myDestinationBankCode = myDestinationBankCode;
            this.myChannelCode = myChannelCode;
            this.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            this.myAccountName = myAccountName;
            this.myOriginatorName = myOriginatorName;
            this.myNarration = myNarration;
            this.myPaymentReference = myPaymentReference;
            this.myAmount = myAmount;
            this.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CIB_Fundtransfersingleitem_dcResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CIB_Fundtransfersingleitem_dcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CIB_Fundtransfersingleitem_dcResult;
        
        public CIB_Fundtransfersingleitem_dcResponse() {
        }
        
        public CIB_Fundtransfersingleitem_dcResponse(string CIB_Fundtransfersingleitem_dcResult) {
            this.CIB_Fundtransfersingleitem_dcResult = CIB_Fundtransfersingleitem_dcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EbillsFundtransfersingleitem_dc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EbillsFundtransfersingleitem_dcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myDestinationBankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myChannelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myCustDestinationAccountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string myAccountName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string myOriginatorName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string myNarration;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string myPaymentReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string myAmount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string myCustomerSourceAccountNumber;
        
        public EbillsFundtransfersingleitem_dcRequest() {
        }
        
        public EbillsFundtransfersingleitem_dcRequest(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            this.AuthHeader = AuthHeader;
            this.myDestinationBankCode = myDestinationBankCode;
            this.myChannelCode = myChannelCode;
            this.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            this.myAccountName = myAccountName;
            this.myOriginatorName = myOriginatorName;
            this.myNarration = myNarration;
            this.myPaymentReference = myPaymentReference;
            this.myAmount = myAmount;
            this.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EbillsFundtransfersingleitem_dcResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EbillsFundtransfersingleitem_dcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string EbillsFundtransfersingleitem_dcResult;
        
        public EbillsFundtransfersingleitem_dcResponse() {
        }
        
        public EbillsFundtransfersingleitem_dcResponse(string EbillsFundtransfersingleitem_dcResult) {
            this.EbillsFundtransfersingleitem_dcResult = EbillsFundtransfersingleitem_dcResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFPOutwardService_BranchSoapChannel : Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFPOutwardService_BranchSoapClient : System.ServiceModel.ClientBase<Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap>, Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap {
        
        public NFPOutwardService_BranchSoapClient() {
        }
        
        public NFPOutwardService_BranchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFPOutwardService_BranchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFPOutwardService_BranchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFPOutwardService_BranchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleResponse txnstatusquerysingleitem(Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleRequest o) {
            return base.Channel.txnstatusquerysingleitem(o);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleResponse> txnstatusquerysingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.TSQuerySingleRequest o) {
            return base.Channel.txnstatusquerysingleitemAsync(o);
        }
        
        public string GetCustomerCummulativeAmount(string myCustomerSourceAccountNumber) {
            return base.Channel.GetCustomerCummulativeAmount(myCustomerSourceAccountNumber);
        }
        
        public System.Threading.Tasks.Task<string> GetCustomerCummulativeAmountAsync(string myCustomerSourceAccountNumber) {
            return base.Channel.GetCustomerCummulativeAmountAsync(myCustomerSourceAccountNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemResponse Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.BranchNameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest request) {
            return base.Channel.BranchNameEnquirySingleitem(request);
        }
        
        public string BranchNameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myAccountNumber = myAccountNumber;
            inValue.myChannelCode = myChannelCode;
            inValue.mySourceAccountNumber = mySourceAccountNumber;
            Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemResponse retVal = ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).BranchNameEnquirySingleitem(inValue);
            return retVal.BranchNameEnquirySingleitemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemResponse> Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.BranchNameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest request) {
            return base.Channel.BranchNameEnquirySingleitemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemResponse> BranchNameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.BranchNameEnquirySingleitemRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myAccountNumber = myAccountNumber;
            inValue.myChannelCode = myChannelCode;
            inValue.mySourceAccountNumber = mySourceAccountNumber;
            return ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).BranchNameEnquirySingleitemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcResponse Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.BranchFundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest request) {
            return base.Channel.BranchFundtransfersingleitem_dc(request);
        }
        
        public string BranchFundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber, int TranType) {
            Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            inValue.TranType = TranType;
            Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcResponse retVal = ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).BranchFundtransfersingleitem_dc(inValue);
            return retVal.BranchFundtransfersingleitem_dcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcResponse> Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.BranchFundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest request) {
            return base.Channel.BranchFundtransfersingleitem_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcResponse> BranchFundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber, int TranType) {
            Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.BranchFundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            inValue.TranType = TranType;
            return ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).BranchFundtransfersingleitem_dcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemResponse Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.RIB_NameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest request) {
            return base.Channel.RIB_NameEnquirySingleitem(request);
        }
        
        public string RIB_NameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myAccountNumber = myAccountNumber;
            inValue.myChannelCode = myChannelCode;
            inValue.mySourceAccountNumber = mySourceAccountNumber;
            Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemResponse retVal = ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).RIB_NameEnquirySingleitem(inValue);
            return retVal.RIB_NameEnquirySingleitemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemResponse> Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.RIB_NameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest request) {
            return base.Channel.RIB_NameEnquirySingleitemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemResponse> RIB_NameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.RIB_NameEnquirySingleitemRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myAccountNumber = myAccountNumber;
            inValue.myChannelCode = myChannelCode;
            inValue.mySourceAccountNumber = mySourceAccountNumber;
            return ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).RIB_NameEnquirySingleitemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcResponse Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.RIB_Fundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest request) {
            return base.Channel.RIB_Fundtransfersingleitem_dc(request);
        }
        
        public string RIB_Fundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcResponse retVal = ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).RIB_Fundtransfersingleitem_dc(inValue);
            return retVal.RIB_Fundtransfersingleitem_dcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcResponse> Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.RIB_Fundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest request) {
            return base.Channel.RIB_Fundtransfersingleitem_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcResponse> RIB_Fundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.RIB_Fundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            return ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).RIB_Fundtransfersingleitem_dcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemResponse Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.CIB_NameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest request) {
            return base.Channel.CIB_NameEnquirySingleitem(request);
        }
        
        public string CIB_NameEnquirySingleitem(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myAccountNumber = myAccountNumber;
            inValue.myChannelCode = myChannelCode;
            inValue.mySourceAccountNumber = mySourceAccountNumber;
            Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemResponse retVal = ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).CIB_NameEnquirySingleitem(inValue);
            return retVal.CIB_NameEnquirySingleitemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemResponse> Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.CIB_NameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest request) {
            return base.Channel.CIB_NameEnquirySingleitemAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemResponse> CIB_NameEnquirySingleitemAsync(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myAccountNumber, string myChannelCode, string mySourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.CIB_NameEnquirySingleitemRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myAccountNumber = myAccountNumber;
            inValue.myChannelCode = myChannelCode;
            inValue.mySourceAccountNumber = mySourceAccountNumber;
            return ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).CIB_NameEnquirySingleitemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcResponse Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.CIB_Fundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest request) {
            return base.Channel.CIB_Fundtransfersingleitem_dc(request);
        }
        
        public string CIB_Fundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcResponse retVal = ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).CIB_Fundtransfersingleitem_dc(inValue);
            return retVal.CIB_Fundtransfersingleitem_dcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcResponse> Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.CIB_Fundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest request) {
            return base.Channel.CIB_Fundtransfersingleitem_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcResponse> CIB_Fundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.CIB_Fundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            return ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).CIB_Fundtransfersingleitem_dcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcResponse Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.EbillsFundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest request) {
            return base.Channel.EbillsFundtransfersingleitem_dc(request);
        }
        
        public string EbillsFundtransfersingleitem_dc(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcResponse retVal = ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).EbillsFundtransfersingleitem_dc(inValue);
            return retVal.EbillsFundtransfersingleitem_dcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcResponse> Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap.EbillsFundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest request) {
            return base.Channel.EbillsFundtransfersingleitem_dcAsync(request);
        }
        
        public System.Threading.Tasks.Task<Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcResponse> EbillsFundtransfersingleitem_dcAsync(Blend.ProvidusImplementation.NFPOutwardService.AuthHeader AuthHeader, string myDestinationBankCode, string myChannelCode, string myCustDestinationAccountNumber, string myAccountName, string myOriginatorName, string myNarration, string myPaymentReference, string myAmount, string myCustomerSourceAccountNumber) {
            Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest inValue = new Blend.ProvidusImplementation.NFPOutwardService.EbillsFundtransfersingleitem_dcRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.myDestinationBankCode = myDestinationBankCode;
            inValue.myChannelCode = myChannelCode;
            inValue.myCustDestinationAccountNumber = myCustDestinationAccountNumber;
            inValue.myAccountName = myAccountName;
            inValue.myOriginatorName = myOriginatorName;
            inValue.myNarration = myNarration;
            inValue.myPaymentReference = myPaymentReference;
            inValue.myAmount = myAmount;
            inValue.myCustomerSourceAccountNumber = myCustomerSourceAccountNumber;
            return ((Blend.ProvidusImplementation.NFPOutwardService.NFPOutwardService_BranchSoap)(this)).EbillsFundtransfersingleitem_dcAsync(inValue);
        }
        
        public double GetNIBSSCharges(double myAmountCharge) {
            return base.Channel.GetNIBSSCharges(myAmountCharge);
        }
        
        public System.Threading.Tasks.Task<double> GetNIBSSChargesAsync(double myAmountCharge) {
            return base.Channel.GetNIBSSChargesAsync(myAmountCharge);
        }
        
        public string[] GetNFPBanks() {
            return base.Channel.GetNFPBanks();
        }
        
        public System.Threading.Tasks.Task<string[]> GetNFPBanksAsync() {
            return base.Channel.GetNFPBanksAsync();
        }
    }
}
